In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

# Creating series and comparing them

In [2]:
# using pandas to compare the two series
series1 = pd.Series([4, 65, 436, 3, 9])
series2 = pd.Series([7, 0, 3, 897, 9])

# Compare the elements of the two series
comparison = series1 == series2

# Display the comparison result
print(comparison)

0    False
1    False
2    False
3    False
4     True
dtype: bool

# Carrying out operations on series created

In [3]:
# Created sample Series
series1 = pd.Series([2, 4, 6, 8, 14])
series2 = pd.Series([1, 3, 5, 7, 9])


addition = series1 + series2
print("Addition:")
print(addition)


subtraction = series1 - series2
print("\nSubtraction:")
print(subtraction)

multiplication = series1 * series2
print("\nMultiplication:")
print(multiplication)



division = series1 / series2
print("\nDivision:")
print(division)

Addition:
0     3
1     7
2    11
3    15
4    23
dtype: int64

Subtraction:
0    1
1    1
2    1
3    1
4    5
dtype: int64

Multiplication:
0      2
1     12
2     30
3     56
4    126
dtype: int64

Division:
0    2.000000
1    1.333333
2    1.200000
3    1.142857
4    1.555556
dtype: float64

# Converting a dictionary to serie

In [4]:
# given the dictionary1,to convert dictionary to Series;
dictionary1 = {'Josh': 24, 'Sam': 36, 'Peace': 19, 'Charles': 65, 'Tom': 44}
converted_dictionary = pd.Series(dictionary1)
print(converted_dictionary)

Josh       24
Sam        36
Peace      19
Charles    65
Tom        44
dtype: int64

# Converting the serie into an array

In [5]:
# converting the serie into an array
series1 = pd.Series(['Love', 800, 'Joy', 789.9, 'Peace', True])
array1 = np.array(series1)
print(array1)

['Love' 800 'Joy' 789.9 'Peace' True]

# Loading the dataset

In [6]:
#using the AfricaCupofNationsMatches dataset
match=pd.read_csv("AfricaCupofNationsMatches.csv")
match

,Year,Date,Time,HomeTeam,AwayTeam,HomeTeamGoals,AwayTeamGoals,Stage,SpecialWinConditions,Stadium,City,Attendance
0,1957,10-Feb-57,NaN,Sudan,Egypt,1.0,2.0,Semifinals,NaN,Municipal Stadium,Khartoum,30000.0
1,1957,10-Feb-57,NaN,Ethiopia,South Africa,NaN,NaN,Semifinals,Ethiopia wins due to disqualification of othe...,NaN,NaN,NaN
2,1957,16-Feb-57,NaN,Egypt,Ethiopia,4.0,0.0,Final,NaN,Municipal Stadium,Khartoum,30000.0
3,1959,22-May-59,NaN,Egypt,Ethiopia,4.0,0.0,Final Tournament,NaN,Prince Farouk Stadium,Cairo,30000.0
4,1959,25-May-59,NaN,Sudan,Ethiopia,1.0,0.0,Final Tournament,NaN,Prince Farouk Stadium,Cairo,20000.0
...,...,...,...,...,...,...,...,...,...,...,...,...
617,2019,11 July 2019 (2019-07-11),21:00,Madagascar,Tunisia,0.0,3.0,Quarter-finals,NaN,Al Salam Stadium,Cairo,7568.0
618,2019,14 July 2019 (2019-07-14),18:00,Senegal,Tunisia,1.0,0.0,Semi-finals,win after extra time,30 June Stadium,Cairo,9143.0
619,2019,14 July 2019 (2019-07-14),21:00,Algeria,Nigeria,2.0,1.0,Semi-finals,NaN,Cairo International Stadium,Cairo,49775.0
620,2019,17 July 2019 (2019-07-17),21:00,Tunisia,Nigeria,0.0,1.0,Third place play-off,NaN,Al Salam Stadium,Cairo,6340.0
621,2019,19 July 2019 (2019-07-19),21:00,Senegal,Algeria,0.0,1.0,Final,NaN,Cairo International Stadium,Cairo,75000.0

In [10]:
match['HomeTeamGoals'].unique()

array([ 1., nan,  4.,  2.,  3.,  6.,  0.,  5.])

In [ ]:
# using the given dataset

In [11]:
match1=pd.read_csv("AfricaCupofNationsMatches.csv")
match1

,Year,Date,Time,HomeTeam,AwayTeam,HomeTeamGoals,AwayTeamGoals,Stage,SpecialWinConditions,Stadium,City,Attendance
0,1957,10-Feb-57,NaN,Sudan,Egypt,1.0,2.0,Semifinals,NaN,Municipal Stadium,Khartoum,30000.0
1,1957,10-Feb-57,NaN,Ethiopia,South Africa,NaN,NaN,Semifinals,Ethiopia wins due to disqualification of othe...,NaN,NaN,NaN
2,1957,16-Feb-57,NaN,Egypt,Ethiopia,4.0,0.0,Final,NaN,Municipal Stadium,Khartoum,30000.0
3,1959,22-May-59,NaN,Egypt,Ethiopia,4.0,0.0,Final Tournament,NaN,Prince Farouk Stadium,Cairo,30000.0
4,1959,25-May-59,NaN,Sudan,Ethiopia,1.0,0.0,Final Tournament,NaN,Prince Farouk Stadium,Cairo,20000.0
...,...,...,...,...,...,...,...,...,...,...,...,...
617,2019,11 July 2019 (2019-07-11),21:00,Madagascar,Tunisia,0.0,3.0,Quarter-finals,NaN,Al Salam Stadium,Cairo,7568.0
618,2019,14 July 2019 (2019-07-14),18:00,Senegal,Tunisia,1.0,0.0,Semi-finals,win after extra time,30 June Stadium,Cairo,9143.0
619,2019,14 July 2019 (2019-07-14),21:00,Algeria,Nigeria,2.0,1.0,Semi-finals,NaN,Cairo International Stadium,Cairo,49775.0
620,2019,17 July 2019 (2019-07-17),21:00,Tunisia,Nigeria,0.0,1.0,Third place play-off,NaN,Al Salam Stadium,Cairo,6340.0
621,2019,19 July 2019 (2019-07-19),21:00,Senegal,Algeria,0.0,1.0,Final,NaN,Cairo International Stadium,Cairo,75000.0

In [12]:
match=pd.read_csv("AfricaCupofNationsMatches.csv")
match.head(7)

,Year,Date,Time,HomeTeam,AwayTeam,HomeTeamGoals,AwayTeamGoals,Stage,SpecialWinConditions,Stadium,City,Attendance
0,1957,10-Feb-57,NaN,Sudan,Egypt,1.0,2.0,Semifinals,NaN,Municipal Stadium,Khartoum,30000.0
1,1957,10-Feb-57,NaN,Ethiopia,South Africa,NaN,NaN,Semifinals,Ethiopia wins due to disqualification of othe...,NaN,NaN,NaN
2,1957,16-Feb-57,NaN,Egypt,Ethiopia,4.0,0.0,Final,NaN,Municipal Stadium,Khartoum,30000.0
3,1959,22-May-59,NaN,Egypt,Ethiopia,4.0,0.0,Final Tournament,NaN,Prince Farouk Stadium,Cairo,30000.0
4,1959,25-May-59,NaN,Sudan,Ethiopia,1.0,0.0,Final Tournament,NaN,Prince Farouk Stadium,Cairo,20000.0
5,1959,29-May-59,NaN,Egypt,Sudan,2.0,1.0,Final Tournament,NaN,Prince Farouk Stadium,Cairo,30000.0
6,1962,14-Jan-62,NaN,Ethiopia,Tunisia,4.0,2.0,Semifinals,NaN,Hailé Sélassié Stadium,Addis Ababa,30000.0

# Selecting the wanted columns

In [13]:

desired_columns = match1[['HomeTeam', 'AwayTeam', 'HomeTeamGoals', 'AwayTeamGoals']]
(desired_columns)

        HomeTeam       AwayTeam  HomeTeamGoals  AwayTeamGoals
0         Sudan           Egypt            1.0            2.0
1      Ethiopia    South Africa            NaN            NaN
2         Egypt        Ethiopia            4.0            0.0
3          Egypt       Ethiopia            4.0            0.0
4         Sudan        Ethiopia            1.0            0.0
..           ...            ...            ...            ...
617  Madagascar         Tunisia            0.0            3.0
618     Senegal         Tunisia            1.0            0.0
619     Algeria         Nigeria            2.0            1.0
620     Tunisia         Nigeria            0.0            1.0
621     Senegal         Algeria            0.0            1.0

[622 rows x 4 columns]

# Selecting where egypt appears

In [15]:

egypt_rows = match1[(match1['HomeTeam'] == 'Egypt' ) | (match1['AwayTeam'] == 'Egypt')]

# Print the selected rows
(egypt_rows)

,Year,Date,Time,HomeTeam,AwayTeam,HomeTeamGoals,AwayTeamGoals,Stage,SpecialWinConditions,Stadium,City,Attendance
3,1959,22-May-59,NaN,Egypt,Ethiopia,4.0,0.0,Final Tournament,NaN,Prince Farouk Stadium,Cairo,30000.0
5,1959,29-May-59,NaN,Egypt,Sudan,2.0,1.0,Final Tournament,NaN,Prince Farouk Stadium,Cairo,30000.0
7,1962,18-Jan-62,NaN,Egypt,Uganda,2.0,1.0,Semifinals,NaN,Hailé Sélassié Stadium,Addis Ababa,30000.0
9,1962,21-Jan-62,NaN,Ethiopia,Egypt,4.0,2.0,Final,win after extra time,Hailé Sélassié Stadium,Addis Ababa,NaN
13,1963,24-Nov-63,NaN,Egypt,Nigeria,6.0,3.0,Group B,NaN,Kumasi Sports Stadium,Kumasi,NaN
14,1963,26-Nov-63,NaN,Egypt,Sudan,2.0,2.0,Group B,NaN,Kumasi Sports Stadium,Kumasi,NaN
16,1963,30-Nov-63,NaN,Egypt,Ethiopia,3.0,0.0,Third place match,NaN,Accra Sports Stadium,Accra,NaN

# Counting the number of rows and columns in the dataset

In [16]:
num_rows = match1.shape[0]
num_columns = match1.shape[1]

# Print the results
print("Number of rows:", num_rows)
print("Number of columns:", num_columns)

Number of rows: 622
Number of columns: 12

# Selecting where attendance is missing

In [21]:
missing_attendance=match1[match1["Attendance"].isnull()]
(missing_attendance)

,Year,Date,Time,HomeTeam,AwayTeam,HomeTeamGoals,AwayTeamGoals,Stage,SpecialWinConditions,Stadium,City,Attendance
1,1957,10-Feb-57,NaN,Ethiopia,South Africa,NaN,NaN,Semifinals,Ethiopia wins due to disqualification of othe...,NaN,NaN,NaN
8,1962,20-Jan-62,NaN,Tunisia,Uganda,3.0,0.0,Third place match,NaN,Hailé Sélassié Stadium,Addis Ababa,NaN
9,1962,21-Jan-62,NaN,Ethiopia,Egypt,4.0,2.0,Final,win after extra time,Hailé Sélassié Stadium,Addis Ababa,NaN
10,1963,24-Nov-63,NaN,Ghana,Tunisia,1.0,1.0,Group A,NaN,Accra Sports Stadium,Accra,NaN
11,1963,26-Nov-63,NaN,Ghana,Ethiopia,2.0,0.0,Group A,NaN,Accra Sports Stadium,Accra,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
565,2017,29 January 2017 (2017-01-29),20:00,Egypt,Morocco,1.0,0.0,Quarter-finals,NaN,Stade de Port-Gentil,Port-Gentil,NaN
566,2017,1 February 2017 (2017-02-01),20:00,Burkina Faso,Egypt,1.0,1.0,Semi-finals,Egypt win on Penalities 3-4,Stade de l'Amitié,Libreville,NaN
567,2017,2 February 2017 (2017-02-02),20:00,Cameroon,Ghana,2.0,0.0,Semi-finals,NaN,Stade de Franceville,Franceville,NaN
568,2017,4 February 2017 (2017-02-04),20:00,Burkina Faso,Ghana,1.0,0.0,Third place play-off,NaN,Stade de Port-Gentil,Port-Gentil,NaN
569,2017,5 February 2017 (2017-02-05),20:00,Egypt,Cameroon,1.0,2.0,Final,NaN,Stade de l'Amitié,Libreville,NaN

#selecting the rows in the homeTeamGoals columns between 3and 6 inclusive

In [25]:
filtered_df = match1[match1['HomeTeamGoals'].between(3, 6)]

# Print the resulting DataFrame
(filtered_df)

,Year,Date,Time,HomeTeam,AwayTeam,HomeTeamGoals,AwayTeamGoals,Stage,SpecialWinConditions,Stadium,City,Attendance
2,1957,16-Feb-57,NaN,Egypt,Ethiopia,4.0,0.0,Final,NaN,Municipal Stadium,Khartoum,30000.0
3,1959,22-May-59,NaN,Egypt,Ethiopia,4.0,0.0,Final Tournament,NaN,Prince Farouk Stadium,Cairo,30000.0
6,1962,14-Jan-62,NaN,Ethiopia,Tunisia,4.0,2.0,Semifinals,NaN,Hailé Sélassié Stadium,Addis Ababa,30000.0
8,1962,20-Jan-62,NaN,Tunisia,Uganda,3.0,0.0,Third place match,NaN,Hailé Sélassié Stadium,Addis Ababa,NaN
9,1962,21-Jan-62,NaN,Ethiopia,Egypt,4.0,2.0,Final,win after extra time,Hailé Sélassié Stadium,Addis Ababa,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
553,2017,20 January 2017 (2017-01-20),20:00,Morocco,Togo,3.0,1.0,Group C,NaN,Stade d'Oyem,Oyem,NaN
585,2019,27 June 2019 (2019-06-27),22:00,Kenya,Tanzania,3.0,2.0,Group C,NaN,30 June Stadium,Cairo,7233.0
595,2019,24 June 2019 (2019-06-24),22:00,Mali,Mauritania,4.0,1.0,Group E,NaN,Suez Stadium,Suez,6202.0
608,2019,6 July 2019 (2019-07-06),18:00,Nigeria,Cameroon,3.0,2.0,Round of 16,NaN,Alexandria Stadium,Alexandria,10000.0
611,2019,7 July 2019 (2019-07-07),21:00,Algeria,Guinea,3.0,0.0,Round of 16,NaN,30 June Stadium,Cairo,8205.0

# Changing the 3th row in the awayTeamGoals column to 10

In [27]:
# 2 is for the index of that row
match1.at[2,"AwayTeamGoals"]= 10
match1

,Year,Date,Time,HomeTeam,AwayTeam,HomeTeamGoals,AwayTeamGoals,Stage,SpecialWinConditions,Stadium,City,Attendance
0,1957,10-Feb-57,NaN,Sudan,Egypt,1.0,2.0,Semifinals,NaN,Municipal Stadium,Khartoum,30000.0
1,1957,10-Feb-57,NaN,Ethiopia,South Africa,NaN,NaN,Semifinals,Ethiopia wins due to disqualification of othe...,NaN,NaN,NaN
2,1957,16-Feb-57,NaN,Egypt,Ethiopia,4.0,10.0,Final,NaN,Municipal Stadium,Khartoum,30000.0
3,1959,22-May-59,NaN,Egypt,Ethiopia,4.0,0.0,Final Tournament,NaN,Prince Farouk Stadium,Cairo,30000.0
4,1959,25-May-59,NaN,Sudan,Ethiopia,1.0,0.0,Final Tournament,NaN,Prince Farouk Stadium,Cairo,20000.0
...,...,...,...,...,...,...,...,...,...,...,...,...
617,2019,11 July 2019 (2019-07-11),21:00,Madagascar,Tunisia,0.0,3.0,Quarter-finals,NaN,Al Salam Stadium,Cairo,7568.0
618,2019,14 July 2019 (2019-07-14),18:00,Senegal,Tunisia,1.0,0.0,Semi-finals,win after extra time,30 June Stadium,Cairo,9143.0
619,2019,14 July 2019 (2019-07-14),21:00,Algeria,Nigeria,2.0,1.0,Semi-finals,NaN,Cairo International Stadium,Cairo,49775.0
620,2019,17 July 2019 (2019-07-17),21:00,Tunisia,Nigeria,0.0,1.0,Third place play-off,NaN,Al Salam Stadium,Cairo,6340.0
621,2019,19 July 2019 (2019-07-19),21:00,Senegal,Algeria,0.0,1.0,Final,NaN,Cairo International Stadium,Cairo,75000.0

# sorting the first column in ascending order and the other descending order

In [31]:
sort_dataframe=match1.sort_values(by=['HomeTeam','HomeTeamGoals'],ascending=[True,False])
sort_dataframe

,Year,Date,Time,HomeTeam,AwayTeam,HomeTeamGoals,AwayTeamGoals,Stage,SpecialWinConditions,Stadium,City,Attendance
205,1990,2-Mar-90,NaN,Algeria,Nigeria,5.0,1.0,Group A,NaN,Stade 5 Juillet 1962,Algiers,85000.0
29,1968,14-Jan-68,NaN,Algeria,Uganda,4.0,0.0,Group A,NaN,Hailé Sélassié Stadium,Addis Ababa,25000.0
135,1980,16-Mar-80,NaN,Algeria,Guinea,3.0,2.0,Group B,NaN,Liberty Stadium,Ibadan,20000.0
164,1984,5-Mar-84,NaN,Algeria,Malawi,3.0,0.0,Group B,NaN,Stade Bouaké,Bouaké,10000.0
171,1984,17-Mar-84,NaN,Algeria,Egypt,3.0,1.0,Third place match,NaN,Stade Félix Houphouët-Boigny,Abidjan,500.0
...,...,...,...,...,...,...,...,...,...,...,...,...
521,2012,12-Feb-12,20:30[note 1],Zambia,Ivory Coast,0.0,0.0,Final,Zambia win on Penalities 8-7,Stade d'Angondjé,Libreville,40000.0
549,2017,23 January 2017 (2017-01-23),20:00,Zimbabwe,Tunisia,2.0,4.0,Group B,NaN,Stade de l'Amitié,Libreville,NaN
398,2004,25-Jan-04,16:30,Zimbabwe,Egypt,1.0,2.0,Group C,NaN,Stade Taïeb El Mhiri,Sfax,22000.0
437,2006,23-Jan-06,20:00,Zimbabwe,Senegal,0.0,2.0,Group D,NaN,Port Said Stadium,Port Said,15000.0
575,2019,30 June 2019 (2019-06-30),21:00,Zimbabwe,DR Congo,0.0,4.0,Group A,NaN,30 June Stadium,Cairo,4364.0

# Getting a list from the dataframe column headers

In [33]:
column_headers = match1.columns.tolist()
(column_headers)

['Year',
 'Date ',
 'Time ',
 'HomeTeam',
 'AwayTeam',
 'HomeTeamGoals',
 'AwayTeamGoals',
 'Stage',
 'SpecialWinConditions',
 'Stadium',
 'City',
 'Attendance']

# Appending a new column ot the dataframe

In [83]:
new_column = [true,false]  # Replace with your desired values

# Append the new column to the DataFrame using assign()
df = match1.assign(NewColumn=new_column)

# Print the updated DataFrame
print(df)

NameError: name 'true' is not defined

In [47]:
match1.shape

(625, 13)

# adding 2 rows to your DataFrame.

In [51]:
new_rows = [{'1','2', '3' , '4' '5','6' '8', '8' , '7' '3','0' 'e8' ,'2c','64','79', '92' , '224','665'},
            {'1w', '2cc', '3f' , '4m', '5k','6kj', '8h', '8k', 'd7' 'd3','0y', 'ef8' ,'2c','64hg' '7j9', '9h2' , '2k24', 'sqw'}]

# Adding new rows to the DataFrame
df = match1.append(new_rows, ignore_index=True)

# Displaying the updated DataFrame
(df)

C:\Users\Linda\AppData\Local\Temp\ipykernel_2316\3205616171.py:5: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = match1.append(new_rows, ignore_index=True)

,Year,Date,Time,HomeTeam,AwayTeam,HomeTeamGoals,AwayTeamGoals,Stage,SpecialWinConditions,Stadium,...,6,7,8,9,10,11,12,13,14,15
0,1957.0,10-Feb-57,NaN,Sudan,Egypt,1.0,2.0,Semifinals,NaN,Municipal Stadium,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1957.0,10-Feb-57,NaN,Ethiopia,South Africa,NaN,NaN,Semifinals,Ethiopia wins due to disqualification of othe...,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1957.0,16-Feb-57,NaN,Egypt,Ethiopia,4.0,10.0,Final,NaN,Municipal Stadium,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1959.0,22-May-59,NaN,Egypt,Ethiopia,4.0,0.0,Final Tournament,NaN,Prince Farouk Stadium,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1959.0,25-May-59,NaN,Sudan,Ethiopia,1.0,0.0,Final Tournament,NaN,Prince Farouk Stadium,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
622,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
623,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
624,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
625,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,45,0e8,2,1,224,3,8,665,None,None
626,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,sqw,1w,64hg7j9,9h2,d7d3,2cc,8h,4m,6kj,2k24

# replacing in that column where there is uganda to replace china

In [55]:
match1.loc[match1['AwayTeam'] == 'Uganda', 'AwayTeam'] = 'China'

# Displaying the updated DataFrame
print("\nUpdated DataFrame:")
df

Updated DataFrame:

,Year,Date,Time,HomeTeam,AwayTeam,HomeTeamGoals,AwayTeamGoals,Stage,SpecialWinConditions,Stadium,...,6,7,8,9,10,11,12,13,14,15
0,1957.0,10-Feb-57,NaN,Sudan,Egypt,1.0,2.0,Semifinals,NaN,Municipal Stadium,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1957.0,10-Feb-57,NaN,Ethiopia,South Africa,NaN,NaN,Semifinals,Ethiopia wins due to disqualification of othe...,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1957.0,16-Feb-57,NaN,Egypt,Ethiopia,4.0,10.0,Final,NaN,Municipal Stadium,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1959.0,22-May-59,NaN,Egypt,Ethiopia,4.0,0.0,Final Tournament,NaN,Prince Farouk Stadium,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1959.0,25-May-59,NaN,Sudan,Ethiopia,1.0,0.0,Final Tournament,NaN,Prince Farouk Stadium,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
622,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
623,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
624,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
625,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,45,0e8,2,1,224,3,8,665,None,None
626,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,sqw,1w,64hg7j9,9h2,d7d3,2cc,8h,4m,6kj,2k24

In [53]:
#eliminate the white space first to work out
match1['AwayTeam']=match1['AwayTeam'].str.strip().replace('Uganda','China')
match1.head(20)

,Year,Date,Time,HomeTeam,AwayTeam,HomeTeamGoals,AwayTeamGoals,Stage,SpecialWinConditions,Stadium,City,Attendance,0
0,1957.0,10-Feb-57,NaN,Sudan,Egypt,1.0,2.0,Semifinals,NaN,Municipal Stadium,Khartoum,30000.0,NaN
1,1957.0,10-Feb-57,NaN,Ethiopia,South Africa,NaN,NaN,Semifinals,Ethiopia wins due to disqualification of othe...,NaN,NaN,NaN,NaN
2,1957.0,16-Feb-57,NaN,Egypt,Ethiopia,4.0,10.0,Final,NaN,Municipal Stadium,Khartoum,30000.0,NaN
3,1959.0,22-May-59,NaN,Egypt,Ethiopia,4.0,0.0,Final Tournament,NaN,Prince Farouk Stadium,Cairo,30000.0,NaN
4,1959.0,25-May-59,NaN,Sudan,Ethiopia,1.0,0.0,Final Tournament,NaN,Prince Farouk Stadium,Cairo,20000.0,NaN
5,1959.0,29-May-59,NaN,Egypt,Sudan,2.0,1.0,Final Tournament,NaN,Prince Farouk Stadium,Cairo,30000.0,NaN
6,1962.0,14-Jan-62,NaN,Ethiopia,Tunisia,4.0,2.0,Semifinals,NaN,Hailé Sélassié Stadium,Addis Ababa,30000.0,NaN
7,1962.0,18-Jan-62,NaN,Egypt,China,2.0,1.0,Semifinals,NaN,Hailé Sélassié Stadium,Addis Ababa,30000.0,NaN
8,1962.0,20-Jan-62,NaN,Tunisia,China,3.0,0.0,Third place match,NaN,Hailé Sélassié Stadium,Addis Ababa,NaN,NaN
9,1962.0,21-Jan-62,NaN,Ethiopia,Egypt,4.0,2.0,Final,win after extra time,Hailé Sélassié Stadium,Addis Ababa,NaN,NaN
10,1963.0,24-Nov-63,NaN,Ghana,Tunisia,1.0,1.0,Group A,NaN,Accra Sports Stadium,Accra,NaN,NaN
11,1963.0,26-Nov-63,NaN,Ghana,Ethiopia,2.0,0.0,Group A,NaN,Accra Sports Stadium,Accra,NaN,NaN
12,1963.0,28-Nov-63,NaN,Ethiopia,Tunisia,4.0,2.0,Group A,NaN,Accra Sports Stadium,Accra,NaN,NaN
13,1963.0,24-Nov-63,NaN,Egypt,Nigeria,6.0,3.0,Group B,NaN,Kumasi Sports Stadium,Kumasi,NaN,NaN
14,1963.0,26-Nov-63,NaN,Egypt,Sudan,2.0,2.0,Group B,NaN,Kumasi Sports Stadium,Kumasi,NaN,NaN
15,1963.0,28-Nov-63,NaN,Sudan,Nigeria,4.0,0.0,Group B,NaN,Kumasi Sports Stadium,Kumasi,NaN,NaN
16,1963.0,30-Nov-63,NaN,Egypt,Ethiopia,3.0,0.0,Third place match,NaN,Accra Sports Stadium,Accra,NaN,NaN
17,1963.0,1-Dec-63,NaN,Ghana,Sudan,3.0,0.0,Final,NaN,Accra Sports Stadium,Accra,NaN,NaN
18,1965.0,12-Nov-65,NaN,Tunisia,Ethiopia,4.0,0.0,Group A,NaN,Stade Chedli Zouiten,Tunis,16000.0,NaN
19,1965.0,14-Nov-65,NaN,Senegal,Tunisia,0.0,0.0,Group A,NaN,Stade Chedli Zouiten,Tunis,NaN,NaN

# Resetting index in your DataFrame.

In [56]:
match1=match1.reset_index(drop=True)
match1

,Year,Date,Time,HomeTeam,AwayTeam,HomeTeamGoals,AwayTeamGoals,Stage,SpecialWinConditions,Stadium,City,Attendance,0
0,1957.0,10-Feb-57,NaN,Sudan,Egypt,1.0,2.0,Semifinals,NaN,Municipal Stadium,Khartoum,30000.0,NaN
1,1957.0,10-Feb-57,NaN,Ethiopia,South Africa,NaN,NaN,Semifinals,Ethiopia wins due to disqualification of othe...,NaN,NaN,NaN,NaN
2,1957.0,16-Feb-57,NaN,Egypt,Ethiopia,4.0,10.0,Final,NaN,Municipal Stadium,Khartoum,30000.0,NaN
3,1959.0,22-May-59,NaN,Egypt,Ethiopia,4.0,0.0,Final Tournament,NaN,Prince Farouk Stadium,Cairo,30000.0,NaN
4,1959.0,25-May-59,NaN,Sudan,Ethiopia,1.0,0.0,Final Tournament,NaN,Prince Farouk Stadium,Cairo,20000.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
620,2019.0,17 July 2019 (2019-07-17),21:00,Tunisia,Nigeria,0.0,1.0,Third place play-off,NaN,Al Salam Stadium,Cairo,6340.0,NaN
621,2019.0,19 July 2019 (2019-07-19),21:00,Senegal,Algeria,0.0,1.0,Final,NaN,Cairo International Stadium,Cairo,75000.0,NaN
622,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,true
623,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,false
624,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,true

# 15.checking whether the ‘Stadium’ column is present in your DataFrame or not.

In [62]:
if 'Stadium'in match1.columns:
        print("stadium present")
else:
        print("stadium not found")

stadium present

# 16.converting the datatype of AwayTeamgoals column type a float

In [64]:
match1["AwayTeamGoals"]=match1["AwayTeamGoals"].astype(float)
match1

,Year,Date,Time,HomeTeam,AwayTeam,HomeTeamGoals,AwayTeamGoals,Stage,SpecialWinConditions,Stadium,City,Attendance,0
0,1957.0,10-Feb-57,NaN,Sudan,Egypt,1.0,2.0,Semifinals,NaN,Municipal Stadium,Khartoum,30000.0,NaN
1,1957.0,10-Feb-57,NaN,Ethiopia,South Africa,NaN,NaN,Semifinals,Ethiopia wins due to disqualification of othe...,NaN,NaN,NaN,NaN
2,1957.0,16-Feb-57,NaN,Egypt,Ethiopia,4.0,10.0,Final,NaN,Municipal Stadium,Khartoum,30000.0,NaN
3,1959.0,22-May-59,NaN,Egypt,Ethiopia,4.0,0.0,Final Tournament,NaN,Prince Farouk Stadium,Cairo,30000.0,NaN
4,1959.0,25-May-59,NaN,Sudan,Ethiopia,1.0,0.0,Final Tournament,NaN,Prince Farouk Stadium,Cairo,20000.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
620,2019.0,17 July 2019 (2019-07-17),21:00,Tunisia,Nigeria,0.0,1.0,Third place play-off,NaN,Al Salam Stadium,Cairo,6340.0,NaN
621,2019.0,19 July 2019 (2019-07-19),21:00,Senegal,Algeria,0.0,1.0,Final,NaN,Cairo International Stadium,Cairo,75000.0,NaN
622,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,true
623,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,false
624,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,true

In [74]:
# we can use negative indexing to remove the last 10 rows
df=match1[:-10]
df

,Year,Date,Time,HomeTeam,AwayTeam,HomeTeamGoals,AwayTeamGoals,Stage,SpecialWinConditions,Stadium,City,Attendance,0
0,1957.0,10-Feb-57,NaN,Sudan,Egypt,1.0,2.0,Semifinals,NaN,Municipal Stadium,Khartoum,30000.0,NaN
1,1957.0,10-Feb-57,NaN,Ethiopia,South Africa,NaN,NaN,Semifinals,Ethiopia wins due to disqualification of othe...,NaN,NaN,NaN,NaN
2,1957.0,16-Feb-57,NaN,Egypt,Ethiopia,4.0,10.0,Final,NaN,Municipal Stadium,Khartoum,30000.0,NaN
3,1959.0,22-May-59,NaN,Egypt,Ethiopia,4.0,0.0,Final Tournament,NaN,Prince Farouk Stadium,Cairo,30000.0,NaN
4,1959.0,25-May-59,NaN,Sudan,Ethiopia,1.0,0.0,Final Tournament,NaN,Prince Farouk Stadium,Cairo,20000.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
610,2019.0,7 July 2019 (2019-07-07),18:00,Madagascar,DR Congo,2.0,2.0,Round of 16,Madagascar win on Penalities 4-2,Alexandria Stadium,Alexandria,5890.0,NaN
611,2019.0,7 July 2019 (2019-07-07),21:00,Algeria,Guinea,3.0,0.0,Round of 16,NaN,30 June Stadium,Cairo,8205.0,NaN
612,2019.0,8 July 2019 (2019-07-08),18:00,Mali,Ivory Coast,0.0,1.0,Round of 16,NaN,Suez Stadium,Suez,7672.0,NaN
613,2019.0,8 July 2019 (2019-07-08),21:00,Ghana,Tunisia,1.0,1.0,Round of 16,Tunisia win on Penalities 4-5,Ismailia Stadium,Ismailia,8890.0,NaN
614,2019.0,10 July 2019 (2019-07-10),18:00,Senegal,Benin,1.0,0.0,Quarter-finals,NaN,30 June Stadium,Cairo,5798.0,NaN

In [71]:
#using the tail()
match=match1.drop(match1.tail(10).index)
match

,Year,Date,Time,HomeTeam,AwayTeam,HomeTeamGoals,AwayTeamGoals,Stage,SpecialWinConditions,Stadium,City,Attendance,0
0,1957.0,10-Feb-57,NaN,Sudan,Egypt,1.0,2.0,Semifinals,NaN,Municipal Stadium,Khartoum,30000.0,NaN
1,1957.0,10-Feb-57,NaN,Ethiopia,South Africa,NaN,NaN,Semifinals,Ethiopia wins due to disqualification of othe...,NaN,NaN,NaN,NaN
2,1957.0,16-Feb-57,NaN,Egypt,Ethiopia,4.0,10.0,Final,NaN,Municipal Stadium,Khartoum,30000.0,NaN
3,1959.0,22-May-59,NaN,Egypt,Ethiopia,4.0,0.0,Final Tournament,NaN,Prince Farouk Stadium,Cairo,30000.0,NaN
4,1959.0,25-May-59,NaN,Sudan,Ethiopia,1.0,0.0,Final Tournament,NaN,Prince Farouk Stadium,Cairo,20000.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
610,2019.0,7 July 2019 (2019-07-07),18:00,Madagascar,DR Congo,2.0,2.0,Round of 16,Madagascar win on Penalities 4-2,Alexandria Stadium,Alexandria,5890.0,NaN
611,2019.0,7 July 2019 (2019-07-07),21:00,Algeria,Guinea,3.0,0.0,Round of 16,NaN,30 June Stadium,Cairo,8205.0,NaN
612,2019.0,8 July 2019 (2019-07-08),18:00,Mali,Ivory Coast,0.0,1.0,Round of 16,NaN,Suez Stadium,Suez,7672.0,NaN
613,2019.0,8 July 2019 (2019-07-08),21:00,Ghana,Tunisia,1.0,1.0,Round of 16,Tunisia win on Penalities 4-5,Ismailia Stadium,Ismailia,8890.0,NaN
614,2019.0,10 July 2019 (2019-07-10),18:00,Senegal,Benin,1.0,0.0,Quarter-finals,NaN,30 June Stadium,Cairo,5798.0,NaN

# changing the order of the column headers

In [75]:
match1.columns

Index([                'Year',                'Date ',                'Time ',
                   'HomeTeam',             'AwayTeam',        'HomeTeamGoals',
              'AwayTeamGoals',                'Stage', 'SpecialWinConditions',
                    'Stadium',                 'City',           'Attendance',
                            0],
      dtype='object')

In [77]:
new_dataframe=([ 'Year',  'Stage', 'Date ',   'Stadium',   'City','AwayTeamGoals',   'Time ', 'AwayTeam', 'HomeTeam','HomeTeamGoals',  'Attendance',  'SpecialWinConditions'])
new_dataframe

new1=pd.read_csv("")

['Year',
 'Stage',
 'Date ',
 'Stadium',
 'City',
 'AwayTeamGoals',
 'Time ',
 'AwayTeam',
 'HomeTeam',
 'HomeTeamGoals',
 'Attendance',
 'SpecialWinConditions']